version: '3'
services:
  strapi:
    # image: strapi/strapi
    build: ./app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: gatsbybase
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: secret
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    networks:
      - postgres_link
  web:
    build: ./web
    ports:
      - '8080:8000'
networks:
  postgres_link:
    external:
      name: postgresql_default